# Generated by Django 3.2 on 2022-12-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_newsletter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
