# Generated by Django 3.2 on 2023-01-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_name',
        ),
    ]
